### ISSUE TITLE
Currency uppercase

### ISSUE THREAD

**Issue by herrerameri** [rsksmart/rsk-explorer#20]
Use currency in upper case -> SBTC

**Comment by emiliorizzo** [comment]
`diff --git a/src/filters/NumberFilters.js b/src/filters/NumberFilters.js
index b732f83..829e959 100644
--- a/src/filters/NumberFilters.js
+++ b/src/filters/NumberFilters.js
@@ -48,7 +48,7 @@ export const wei = Vue.filter('wei', (value) => {
 })
 
 export const sbtc = Vue.filter('sbtc', (value) => {
-  return value + ' sbtc'
+  return value + ' SBTC'
 })
 
 export const round = Vue.filter('round', (value, digits) => {`
