### ISSUE TITLE
Search box dissappear in mobile version

### ISSUE THREAD

**Issue by herrerameri** [rsksmart/rsk-explorer#50]
![screenshot_20180827-131320_chrome](https://user-images.githubusercontent.com/22835487/44671163-1b9d9e00-a9fb-11e8-9055-4885dd8eae8f.jpg)

**Comment by emiliorizzo** [comment]
The searchbox is hidden when the screen width < 480px

https://github.com/rsksmart/rsk-explorer/blob/fa16b4e40cf538ed20467e36fa27c13f838a22de/src/lib/styl/header.styl#L68

https://github.com/rsksmart/rsk-explorer/blob/fa16b4e40cf538ed20467e36fa27c13f838a22de/src/lib/styl/header.styl#L147
