### ISSUE TITLE
Dockerize

### ISSUE THREAD

**Issue by tinchou** [rsksmart/rsk-explorer#59]
The decoupled multi-project structure for the explorer is great, great work :).

One of the downsides is that running the explorer takes some set up work that would be easier with a tool such as Docker Compose.

While not necessary, to make things easier I would suggest merging the two repos and having a directory structure like:

```
.
+-- docker-compose.yml
+-- backend
|   +-- Dockerfile
|   +-- package.json
|   +-- ...
+-- frontend
|   +-- Dockerfile
|   +-- package.json
|   +-- ...
```

**Comment by emiliorizzo** [comment]
https://github.com/rsksmart/rsk-explorer-api/issues/17
