### ISSUE TITLE
Time format

### ISSUE THREAD

**Issue by herrerameri** [rsksmart/rsk-explorer#61]
Change time format to sth like: `hh:mm:ss`

![screenshot from 2018-11-13 11-39-22](https://user-images.githubusercontent.com/22835487/48420301-d99e1180-e738-11e8-9e31-93e578653041.png)

**Comment by emiliorizzo** [comment]
This is the current time format:
![image](https://user-images.githubusercontent.com/3934196/48422985-77480f80-e73e-11e8-960e-1c245febfdf9.png)
