### ISSUE TITLE
handle double-slash in URL (minor UX improvement)

### ISSUE THREAD

**Issue by bguiz** [rsksmart/rsk-explorer#97]
## What

- Redirect URLs with an initial double-slash to the equivalent URL
  - for example `https://explorer.testnet.rsk.co//tx/0xc080215f5e43c21f174e20c698a14cbabf49d4f9a4f6c5a7d5f04b647e6e37e6` -> `https://explorer.testnet.rsk.co/tx/0xc080215f5e43c21f174e20c698a14cbabf49d4f9a4f6c5a7d5f04b647e6e37e6`

## Why

- When a user uses a browser based wallet (e.g. MetaMask) and configures a custom network for RSK:
  - If they enter the **Block Explorer URL (optional)** field as `https://explorer.testnet.rsk.co/`,
  - When they click on **Show in Explorer** (in notifications, etc) from the wallet, a new browser tab opens up with the double slash
  - This double slash page currently renders a blank page 
- Improve the user experience

## Refs

- Related PRs: [DevPortal #297](https://github.com/rsksmart/rsksmart.github.io/pull/297)

**Comment by emiliorizzo** [comment]
Hi @bguiz , thanks for reporting.
I  think the best way to do this is changing the HTTP Server configuration, that solves the double slash problem in any part of the URL.
I've adden an example to the README.

**Comment by bguiz** [comment]
Sounds good @emiliorizzo!
